version: "3.7"

services:
  accounts:
    command: npm run api:development
    depends_on:
      - accounts-neo4j
    environment:
      - JWT_SECRET=secret
      - NEO4J_HOST=bolt://accounts-neo4j:7687
      - NEO4J_PASSWORD=accounts
      - NEO4J_USERNAME=neo4j
      - NODE_ENV=development
      - PORT=4000
    image: node:10-alpine
    volumes:
      - ../../services/accounts:/accounts
    working_dir: /accounts

  accounts-neo4j:
    environment:
      - "NEO4J_AUTH=neo4j/accounts"
    image: neo4j:3.5
    # ports:
    #   - "7474:7474"
    #   - "7687:7687"

  gateway:
    depends_on:
      - accounts
      - inventory
      - products
      - reviews
    entrypoint: ./entrypoint.sh
    environment:
      - JWT_SECRET=secret
      - PORT=4000
    image: node:10-alpine
    ports:
      - 4000:4000
    volumes:
      - ../../services/gateway:/gateway
    working_dir: /gateway

  inventory:
    entrypoint: ./entrypoint.sh
    environment:
      - PORT=4000
    image: node:10-alpine
    volumes:
      - ../../services/inventory:/inventory
    working_dir: /inventory

  products:
    command: npm run api:development
    depends_on:
      - products-neo4j
    environment:
      - NEO4J_HOST=bolt://products-neo4j:7687
      - NEO4J_PASSWORD=products
      - NEO4J_USERNAME=neo4j
      - NODE_ENV=development
      - PORT=4000
    image: node:10-alpine
    volumes:
      - ../../services/products:/products
    working_dir: /products

  products-neo4j:
    environment:
      - "NEO4J_AUTH=neo4j/products"
    image: neo4j:3.5
    # ports:
    #   - "7474:7474"
    #   - "7687:7687"

  reviews:
    entrypoint: ./entrypoint.sh
    environment:
      - PORT=4000
    image: node:10-alpine
    volumes:
      - ../../services/reviews:/reviews
    working_dir: /reviews

  web-app:
    command: npm start
    depends_on:
      - gateway
    image: node:10-alpine
    ports:
      - 3000:3000
    volumes:
      - ../../services/web-app:/web-app
    working_dir: /web-app
