version: "3.7"

services:
  accounts:
    build:
      context: ../../services/accounts
    depends_on:
      - accounts-neo4j
    environment:
      - JWT_SECRET=secret
      - NEO4J_HOST=bolt://accounts-neo4j:7687
      - NEO4J_PASSWORD=accounts
      - NEO4J_USERNAME=neo4j
      - NODE_ENV=production
      - PORT=4000
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "http://localhost:4000/.well-known/apollo/server-health",
        ]

  accounts-neo4j:
    environment:
      - "NEO4J_AUTH=neo4j/accounts"
    image: neo4j:3.5
    # ports:
    #   - "7474:7474"
    #   - "7687:7687"

  gateway:
    build:
      context: ../../services/gateway
    depends_on:
      - accounts
      - inventory
      - products
      - reviews
    environment:
      - JWT_SECRET=secret
      - PORT=4000
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "http://localhost:4000/.well-known/apollo/server-health",
        ]
    ports:
      - 4000:4000
    restart: always
    working_dir: /gateway

  inventory:
    entrypoint: ./entrypoint.sh
    environment:
      - PORT=4000
    image: node:10
    volumes:
      - ../../services/inventory:/inventory
    working_dir: /inventory

  products:
    build:
      context: ../../services/products
    environment:
      - NEO4J_HOST=bolt://products-neo4j:7687
      - NEO4J_PASSWORD=products
      - NEO4J_USERNAME=neo4j
      - NODE_ENV=production
      - PORT=4000
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "http://localhost:4000/.well-known/apollo/server-health",
        ]

  products-neo4j:
    environment:
      - "NEO4J_AUTH=neo4j/products"
    image: neo4j:3.5
    # ports:
    #   - "7474:7474"
    #   - "7687:7687"

  reviews:
    entrypoint: ./entrypoint.sh
    environment:
      - PORT=4000
    image: node:10
    volumes:
      - ../../services/reviews:/reviews
    working_dir: /reviews

  web-app:
    build:
      args:
        - GATEWAY_HOST=http://localhost:4000
      context: ../../services/web-app
    depends_on:
      - gateway
    ports:
      - 3000:80
