name: CI

on: [push]

jobs:
  acceptance-tests:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build service images
        run: docker-compose build
        working-directory: ${{ matrix.directory }}
      - name: Start service containers
        run: |
          docker-compose up -d
          docker-compose logs
          docker-compose ps
        working-directory: ${{ matrix.directory }}
      - name: Wait for products database
        run: ./actions/wait-for-products-database/run.sh
      - name: Create products index
        run: |
          export NEO4J_USERNAME=neo4j
          export NEO4J_PASSWORD=products
          ./actions/create-products-index/run.sh
      - name: Install test dependencies
        run: npm ci
        working-directory: acceptance-tests
      - name: Wait for services to be ready
        run: npm run wait-for-services
        working-directory: acceptance-tests
      - name: Run acceptance tests
        run: npm test -- --verbose
        working-directory: acceptance-tests
    strategy:
      matrix:
        directory: [environments/development, environments/production]

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ matrix.directory }}
      - name: Run unit tests
        run: npm test -- --coverage --verbose
        working-directory: ${{ matrix.directory }}
    strategy:
      matrix:
        directory: [services/accounts, services/products]
