name: CI

on: [push]

jobs:
  acceptance-tests:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Start services
        run: |
          docker-compose up -d
          docker-compose ps
        working-directory: ${{ matrix.directory }}
      - name: Install test dependencies
        run: npm ci
        working-directory: acceptance-tests
      - name: Run acceptance tests
        run: npm test -- --verbose
        working-directory: acceptance-tests
    strategy:
      matrix:
        directory: [environments/production]

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ matrix.directory }}
      - name: Run unit tests
        run: npm test -- --coverage --verbose
        working-directory: ${{ matrix.directory }}
    strategy:
      matrix:
        directory: [services/accounts, services/products]
